default:
  testing: false
  show_live_plot: true
  record_video: false
  sequence:
  - 1
  - 2
  - 3
  - 4
  - 5
  training_levels_file: null
  start_level: 1
  reset_level: false
  buffer_trials: 10
  progression_threshold: 0.9
  progression_threshold_advanced: 0.8
  regression_threshold: 0.2
  level_1_min_trials: 50
  prevent_regression_below_start: true
  n_max_trials: 1500
  iti_duration: 0.4
  punish_duration: 0.5
  min_response_window_s: 2.0
  reward_sound: true
  reward_sound_frequency: 8000
  reward_sound_duration: 0.3
  reward_sound_amplitude: 0.05
  HARDWARE_BNC_TRIAL_START: 1
  HARDWARE_PORT_LEFT: 1
  HARDWARE_PORT_CENTER: 2
  HARDWARE_PORT_RIGHT: 3
  ttl_pulse_duration: 0.01
  barcode_bits: 37
  barcode_bit_duration_ms: 35.0
  barcode_init_duration_ms: 10.0
  barcode_tolerance: 0.25
mode: {}
