# Changes here will be overwritten by Copier
_commit: v0.5.0
_src_path: gh:larsrollik/templatepy
author_email: lars@rollik.me
author_name: Lars B. Rollik
github_repo: murineshiftwork
github_username: larsrollik
project_description: Murine Shift Work — behavioural task acquisition with hardware support.
project_name: murineshiftwork
project_slug: murineshiftwork
python_requires: '3.12'
year: '2026'
