default:
  VALVE_OPENING_TIME_MS: 50.0
  VALVE_NUMBERS:
  - 1
  - 3
  N_FLUSH_CYCLES: 1
  INTER_FLUSH_INTERVAL_S: 1.0
  FLUSH_VALVES_SEQUENTIALLY: false
mode:
  fill:
    VALVE_NUMBERS: [2, 1, 6, 3, 7]
    VALVE_OPENING_TIME_MS: 8000.0
    N_FLUSH_CYCLES: 3
    FLUSH_VALVES_SEQUENTIALLY: true
    INTER_FLUSH_INTERVAL_S: 2.0
  wash:
    VALVE_NUMBERS: [2, 1, 6, 3, 7]
    VALVE_OPENING_TIME_MS: 2000.0
    N_FLUSH_CYCLES: 30
    FLUSH_VALVES_SEQUENTIALLY: true
    INTER_FLUSH_INTERVAL_S: 0.5
  test:
    VALVE_NUMBERS: [2, 1, 6, 3, 7]
    VALVE_OPENING_TIME_MS: 2500.0
    N_FLUSH_CYCLES: 1
    FLUSH_VALVES_SEQUENTIALLY: true
    INTER_FLUSH_INTERVAL_S: 0.5
