TESTING = False

# probabilities = [[k, k[::-1]] for k in itertools.combinations_with_replacement([10,50,90],2)]
# probabilities = [item for subl in probabilities for item in subl]
PROBABILITIES = [
    # (10, 10),
    # (10, 10),
    (10, 50),
    (50, 10),
    (10, 90),
    (90, 10),
    # (50, 50),
    (50, 50),
    (50, 90),
    (90, 50),
    # (90, 90),
    # (90, 90),
]
# PROBABILITIES = [(90, 10), (10, 90)]  # for training
# PROBABILITIES = [(100, 100), (100, 100)]  # for training
# PROBABILITIES = [(100, 0), (0, 100)]  # for training
# PROBABILITIES = [(100, 99), (99, 100)]  # for training

PERFORMANCE_TAU_MOVMEAN = 5  # HOW MANY TRIALS INTO PAST ARE CONSIDERED FOR CURRENT PERFORMANCE ESTIMATE, e.g. for block switches
ALLOW_ONLY_ONE_SIDED_TRANSITIONS = (
    False  # ONLY ONE CHOICE CHANGES PROBABILITY ON A GIVEN BLOCK SWITCH
)
BLOCK_SWITCH_AT_CRITERION = True  #
BLOCK_SWITCH_CRITERION_EXTREME = (
    0.8  # NORMAL BLOCKS REQUIRE CRITERION OF STRONG PREFERENCE
)
BLOCK_SWITCH_CRITERION_MID = 0.6  # 50/50 BLOCKS REQUIRE LOSS OF STRONG PREFERENCE
BLOCK_LENGTH = [40, 60]  # IGNORED IF BLOCK_SWITCH_AT_CRITERION == True
BLOCK_SWITCH_TO_DIFFERENT = True  # ALWAYS SWITCH TO ANOTHER TYPE OF BLOCK. NO REPEATS

N_MAX_TRIALS = 1500

DELAY_UNTIL_CENTER_INIT = [
    0.150,
    0.200,
    0.005,  # 5ms steps
]  # SECONDS, can be float->fixed or list(float, float, float[optional])->range[low,high,step]
# DELAY_UNTIL_CENTER_INIT = .07

DELAY_UNTIL_SIDE_TIMEOUT = 10  # SECONDS
DELAY_UNTIL_SIDE_TIMEOUT_FOR_STOPPING = 1  # side timeout in case it's a stop trial
STATE_DURATION_FINAL = 1  # DELAY TO ALLOW POKE OUT
REWARD_AMOUNT_UL = 2
REWARD_DELAY = 0  # SECONDS

USE_STOP_TRIALS = False  # TRIALS THAT SHOULD GET ABORTED ON STOP CUE
STOP_TRIAL_PROPORTION = 0.3  # PROPORTION OF STOP TRIALS FROM ALL TRIALS

STOP_TRIAL_DELAY_INITIAL = 0.100  # SEC
STOP_TRIAL_DELAY_ADAPTIVE_STEP = 0.010  # SEC
STOP_TRIAL_MIN_MAX = [0.05, 0.3]

STOP_CUE_DURATION = 0.100
STOP_CUE_AMPLITUDE = 0.2  # fixme: lOOK UP PARAMS FROM OPERANT CONDITIONING PROTOCOL
STOP_CUE_ONSET_RAMP = 0.05  # fixme: LOOK UP PARAMS FROM OPERANT CONDITIONING PROTOCOL

PUNISH_STOP_TRIALS = False
PUNISH_STOP_TRIALS_PROPORTION = (
    1  # PROPORTION OF STOP TRIALS TO PUNISH ADDITIONALLY WITH AIR PUFF FROM PORT
)
PUNISH_AIR_DURATION_MS = 200  # PUNISH WITH AIR PUFF FROM PORT

STIMULATION = False
STIMULATION_TRIAL_PROPORTION = 0.2
STIMULATION_TIMEPOINT = "ACTION_INIT"  # ACTION_INIT, INIT2CHOICE, MOVE2CHOICE, OUTCOME_REWARD, OUTCOME_STOP, OUTCOME_PUNISH, OUTCOME_RANDOM
STIMULATION_PULSE_FREQUENCY = 30  # Hertz
STIMULATION_PULSE_DURATION = 0.005
STIMULATION_PULSE_TRAIN = 0.5
STIMULATION_PULSE_DELAY = 0

PLOT_TRIAL_SPAN = 100
PLOT_PERFORMANCE_TAU_MOVEMEAN = 8

SAVE_EACH_N_ITERATIONS = 2

HARDWARE_BNC_TRIAL_START = 1
HARDWARE_BNC_STIMULATION = 2
HARDWARE_PULSEPAL_TRIGGER_CHANNEL = 1
HARDWARE_PULSEPAL_OUTPUT_CHANNEL = 1
HARDWARE_PORT_LIGHT_INTENSITY = 50
HARDWARE_PORT_LIGHT_PORTS = ["center"]  # "side" - selects the ports to illuminate
# VALVE indices: [left valve, right valve], - for both water/air
HARDWARE_VALVES_FOR_WATER = [1, 3]
HARDWARE_VALVES_FOR_AIR = [2, 4]

TTL_IDENTIFIER_SEQUENCE = "sssLss"
TTL_PULSE_DURATION = 0.01
