default:
  required_devices:
    - bpod
    - pulsepal
  barcode_bits: 37
  barcode_bit_duration_ms: 35.0
  barcode_init_duration_ms: 10.0
  barcode_tolerance: 0.25
  stimulation_defaults:
    n_trials: 50
    iti: 1.0
    record_video: false
    laser_power: null
    pulse_duration: 0.001
    pulse_frequency: 40
    pulse_train_duration: 1
    pulse_train_delay: 0
    trigger_channels_for_stimulation:
    - 1
    trigger_mode: gated
    channels_stimulation:
    - 1
    channel_trigger_clock:
    - 4
    reset_stimulation_after_sec: 0.005
    continuous: false
  stimulation:
    default_protocol:
      pulse_duration: 0.001
      pulse_frequency: 40
      pulse_train_duration: 1
mode: {}
